/** Declaration file generated by dts-gen */

export = utp_native;
declare class utp_native {
    constructor();
    address(): any;
    bind(port: number, ip: string | Buffer, onlistening?: Function): any;
    close(cb?: Function): void;
    connect(port: number, host: string | Buffer): any;
    listen(port: number, ip: string | Buffer, onlistening?: Function): void;
    ref(): void;
    send(buf: string | Buffer, offset: number, len: number, port: number, host: string | Buffer, cb?: Function): any;
    unref(): void;
    static client: any;
    static connect(port: number, host: string | Buffer): any;
    static createServer(onconnection?: Function): any;
}
